<?php

/**
 * Implements hook_menu().
 */
function phpbb2drupal_menu() {
  $items = array();

  $items['admin/phpbb2drupal'] = array(
    'title' => 'phpBB to Drupal',
    'access callback' => 'user_access',
    'access arguments' => array('migrate phpBB'),
    'page callback' => 'phpbb2drupal_main',
    'file' => 'phpbb2drupal.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/phpbb2drupal/postconfiguration'] = array(
    'title' => 'Post Migration Configuration',
    'access callback' => 'user_access',
    'access arguments' => array('migrate phpBB'),
    'page callback' => 'phpbb2drupal_postconfiguration',
    'file' => 'phpbb2drupal.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/phpbb2drupal/cleanup'] = array(
    'title' => 'Cleanup',
    'access callback' => 'user_access',
    'access arguments' => array('migrate phpBB'),
    'page callback' => 'phpbb2drupal_cleanup',
    'type' => MENU_CALLBACK,
  );
  $items['admin/phpbb2drupal/migrate'] = array(
    'title' => 'Execute Migration',
    'access callback' => 'user_access',
    'access arguments' => array('migrate phpBB'),
    'page callback' => 'phpbb2drupal_migrate',
    'type' => MENU_CALLBACK,
  );
  $items['admin/phpbb2drupal/reset'] = array(
    'title' => 'Reset phpBB2 database URL',
    'access callback' => 'user_access',
    'access arguments' => array('migrate phpBB'),
    'page callback' => 'phpbb2drupal_reset',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/phpbb2drupal'] = array(
    'title' => 'phpBB2Drupal Settings',
    'access callback' => 'user_access',
    'access arguments' => array('migrate phpBB'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('phpbb2drupal_admin_settings'),
    'file' => 'phpbb2drupal.pages.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function phpbb2drupal_permission() {
  return array(
    'migrate phpBB' => array(
      'title' => t('migrate phpBB'),
      'description' => t('TODO Add a description for \'migrate phpBB\''),
    ),
  );
}

/**
 * Callback admin/phpbb2drupal/reset
 */
function phpbb2drupal_reset() {
  variable_del('phpbb2drupal_db_database');
  variable_del('phpbb2drupal_db_username');
  variable_del('phpbb2drupal_db_password');
  variable_del('phpbb2drupal_db_host');
  variable_del('phpbb2drupal_db_driver');
  variable_del('phpbb2drupal_ready', 0);

  return '<p>' . t('The phpBB2 database URL has been reset. You may now <a href="@configlink">go back to the configuration page</a>.',
      array('@configlink' => url('admin/config/phpbb2drupal'))) . '</p>';
}

/**
 * Callback admin/phpbb2drupal/cleanup
 */
function phpbb2drupal_cleanup() {
  return phpbb2drupal_import_cleanup() . '<p>' . t('Drupal database cleaned.') . '</p>';
}

/**
 * Set database connection for phpBB
 *
 * @return
 *   1 if can connect to phpbb database.
 *
 * BEWARE: if you test using db_connect and the connection
 * fails, the process will die() which is a bit too much since we only
 * want to test. Therefore, the test part of the code is not used, now.
 */
function _phpbb2drupal_db_connect($test = 0) {
  global $databases;

  $same = variable_get('phpbb2drupal_same_db', 1);
  $pre = variable_get('phpbb2drupal_table_prefix', 'phpbb_');

  if ($same) {
    // The phpbb data is in the same database as the drupal data.
    // We simple need to copy databse settings and use the correct phpbb prefix.
    // Code done following guide at http://drupal.org/node/18429.
    $other_database = $databases['default']['default'];
    $other_database['prefix'] = $pre;
    Database::addConnectionInfo('phpbb', 'default', $other_database);
  }
  else{
    $other_database = array(
      'database' => variable_get('phpbb2drupal_db_database', $databases['default']['default']['database']),
      'username' => variable_get('phpbb2drupal_db_username', $databases['default']['default']['username']),
      'password' => variable_get('phpbb2drupal_db_password', $databases['default']['default']['password']),
      'host' => variable_get('phpbb2drupal_db_host', $databases['default']['default']['host']),
      'driver' => variable_get('phpbb2drupal_db_driver', $databases['default']['default']['driver']),
      'prefix' => $pre
    );
    Database::addConnectionInfo('phpbb', 'default', $other_database);
    if ($test) {
      if (!db_connect($databases['phpbb']['default'])) {
        return 0;
      }
    }
  }
  return 1;

}

/**
 * Check if the module is enabled.
 *
 * @return array
 *    $out['html'] = formatted html.
 *    $out['result'] = boolean.
 */
function _phpbb2drupal_check_module($module) {
  $out['html'] = '<ul>';
  $result = module_exists($module);
  $out['result'] = $result;
  if ($result == 1) {
    $out['html'] .= '<li>' . t('Module %module is enabled. OK!', array('%module' => $module)) . '</li>';
  }
  else {
    $out['html'] .= '<li><span class="marker">' . t('Module %module is disabled.', array('%module' => $module)) . '</span></li>';
  }
  $out['html'] .= '</ul>';
  return $out;
}

/**
 * Check if the sql tables are installed.
 *
 * @return array
 *   $out['html'] = formatted html.
 *   $out['result'] = boolean.
 */
function _phpbb2drupal_check_tables( $tables = array(), $db = 'default') {
  _phpbb2drupal_db_connect();

  $out['html'] = '<ul>';
  $out['result'] = 1;
  foreach ($tables as $table) {
    db_set_active($db);

    $result = db_table_exists($table);

    db_set_active('default');
    if ($result) {
      $out['html'] .= '<li>' . t('Table %table: OK!', array('%table' => $table)) . '</li>';
    }
    else {
      $out['html'] .= '<li><span class="marker">' . t('Table <strong>%table</strong> does not exist!', array('%table' => $table)) . '</span></li>';
      $out['result'] = 0;
    }
  }
  $out['html'] .= '</ul>';
  return $out;
}



/**
 * Shows the Migrate page from where the code migration is done. I simply calls the migration form.
 */
function phpbb2drupal_migrate() {
  if (!variable_get('phpbb2drupal_ready', 0)) {
    return '<p>' . t('You cannot migrate the data now. Please <a href="@settings">complete the setup first</a>', array('@settings' => url('admin/config/phpbb2drupal'))) . '</p>';
  }

  $output[] = drupal_get_form('phpbb2drupal_migrate_form');
  return $output;
}

/**
 * The migration form used to import the data.
 */
function phpbb2drupal_migrate_form($form) {
  _phpbb2drupal_db_connect();
  // Causes problems with form api redirect
  //ini_set('display_errors', TRUE);

  // Adjust how long you want the script to run...
  if (!ini_get('safe_mode')) {
    drupal_set_time_limit(variable_get('phpbb2drupal_time_limit', 0));
  }

  $PHPBB2DRUPAL_FUNCTIONS = array(
    'users' => t('Import Users'),
    'categories' => t('Import Categories'),
    'topics' => t('Import Topics'),
    'posts' => t('Import Posts'),
	'url' => t('Transform URLs'),
  );

  $form['import'] = array(
    '#type' => 'select',
    '#title' => t('Next import to perform'),
    // Get default value - if none exists, set the first step as default.
    '#default_value' => isset($_SESSION['phpbb2drupal_selected']) ? $_SESSION['phpbb2drupal_selected'] : 'users',
    '#options' => $PHPBB2DRUPAL_FUNCTIONS,
  );
  $form[] = array(
    '#type' => 'submit',
    '#value' => t('Import'),
  );
  return $form;
}

/**
 * Submit function for the migrate form.
 */
function phpbb2drupal_migrate_form_submit($form, $form_state) {

  switch ($form_state['values']['import']) {
    case 'users':
      phpbb2drupal_import_users();
      if (!variable_get('phpbb2drupal_import_user_successful', 0)) {
        $_SESSION['phpbb2drupal_selected'] = 'users';
      }
      else {
        $_SESSION['phpbb2drupal_selected'] = 'categories';
      }
      break;

    case 'categories':
      phpbb2drupal_import_categories();
      if (!variable_get('phpbb2drupal_import_category_successful', 0)) {
        $_SESSION['phpbb2drupal_selected'] = 'categories';
      }
      else {
        $_SESSION['phpbb2drupal_selected'] = 'topics';
      }
      break;

    case 'topics':
      phpbb2drupal_import_topics();
      if (!variable_get('phpbb2drupal_import_topic_successful', 0)) {
        $_SESSION['phpbb2drupal_selected'] = 'topics';
      }
      else {
        $_SESSION['phpbb2drupal_selected'] = 'posts';
      }
      break;

    case 'posts':
      phpbb2drupal_import_posts();
      if (!variable_get('phpbb2drupal_import_post_successful', 0)) {
        $_SESSION['phpbb2drupal_selected'] = 'posts';
      }
      else {
        $_SESSION['phpbb2drupal_selected'] = 'url';
      }
      break;

    case 'url':
      phpbb2drupal_replace_url();
      if (!variable_get('phpbb2drupal_replace_url_successful', 0)) {
        $_SESSION['phpbb2drupal_selected'] = 'url';
      }
      else {
        drupal_set_message('Congratulations.  Import Finished');
        drupal_set_message('Please visit the ' . l('Post migration configuration', 'admin/phpbb2drupal/postconfiguration') . ' page');
        unset($_SESSION['phpbb2drupal_selected']);
      }
      break;
    default:
      $_SESSION['phpbb2drupal_selected'] = 'users';
      break;
  }
}

/**
 * User Import Functions
 */
function phpbb2drupal_import_users() {
  // check if the user database has been successfully imported
  db_set_active('default');
  if (variable_get('phpbb2drupal_import_user_successful', 0)) {
    drupal_set_message(t('Users already imported successfully'));
    return;
  }

  if (variable_get('phpbb2drupal_import_user_started', 0) == 0) {
    // create temporary tables
    db_set_active('default');

    // create profile fields for icq, aim, msn...etc
    $query = db_insert('profile_field')
      ->fields(array(
        'title', 'name', 'explanation', 'category', 'page', 'type',
 	'weight', 'required', 'register', 'visibility', 'options',
      ));

    $values = array(
      array('YIM', 'user_yim', '', 'Contact', '', 'textfield', 0, 0, 1, 2, ''),
      array('AIM', 'user_aim', '', 'Contact', '', 'textfield', 0, 0, 1, 2, ''),
      array('icq', 'user_icq', '', 'Contact', '', 'textfield', 0, 0, 1, 2, ''),
      array('Website', 'user_website', '', 'Contact', '', 'url', 0, 0, 1, 2, ''),
      array('Location', 'user_from', '', 'Personal', '', 'textfield', 0, 0, 1, 2, ''),
      array('Occupation', 'user_occ', '', 'Personal', '', 'textfield', 0, 0, 1, 2, ''),
      array('Interests', 'user_interests', '', 'Personal', '', 'textfield', 0, 0, 1, 2, ''),
    );
    foreach ($values as $record) {
      $query->values($record);
    } 

    $query->execute();

    variable_set('phpbb2drupal_import_user_started', 1);
  }

  db_set_active('default');
  $drupal_admin = array_shift(user_load_multiple(array(), array('name' => variable_get('phpbb2drupal_admin_user', ''))));
  $id = db_insert('phpbb2drupal_temp_user')
    ->fields(array(
      'user_id' => 2,
      'uid' => $drupal_admin->uid,
  ))
  ->execute();

  $files_path = variable_get('file_directory_path', 'files');
  $pictures_path = variable_get('user_picture_path', 'pictures');
  // FIXME continue here.
  // Insert the users into drupal
  db_set_active('phpbb');
  // Do not get "user_type = 2" as they are not real users - used for anon and for site crawlers.
  $user_ids = db_query('SELECT user_id FROM {users} WHERE ( user_id > :user_id AND user_type <> :user_type ) ORDER BY user_id', array(':user_id' => 2, ':user_type' => 2));

  $user_count = db_query('SELECT COUNT(*) FROM {users} WHERE user_id > :user_id', array(':user_id' => 2))->fetchField();

  if (!$user_count) {
    drupal_set_message(t('There were no users found: Aborting script'), 'error');
    return t('There were no users found: Aborting script.');
  }

  drupal_set_message(t('Found %user_count users: Beginning Import', array('%user_count' => $user_count + 1)));

  $import_spammers = variable_get('phpbb2drupal_import_spammers', 1);

  foreach ($user_ids as $result) {

    db_set_active('phpbb');
    $user = db_query('SELECT * FROM {users} WHERE user_id = :user_id', array(':user_id' => $result->user_id))->fetchObject();

    // If we don't want to import users who have never posted, break this while loop here.
    if ($import_spammers == 1 || $user->user_posts != 0 ) {

      // Make sure the user is has not already been imported
      db_set_active('default');
      $count = db_query('SELECT COUNT(*) FROM {phpbb2drupal_temp_user} WHERE user_id = :user_id', array(':user_id' => $user->user_id))->fetchField();
      if ($count > 0) {
        $user->user_active = 0;
      }

      $user->user_aim = strtr($user->user_aim, array('+' => ' ')); # PHPBB stores spaces as +, replace with ' '
      $user->user_yim = strtr($user->user_yim, array('+' => ' '));
      $user->user_timezone = $user->user_timezone * 60 * 60; # Drupal stores timezones in seconds

      // if the $user->user_avatar_type is not their own image, delete it
      // drupal doesn't have pre-defined avatars.   if we were to import it
      // then multiple people would share the same avatar image and if one user
      // were to changes their avatar then it would change it for everybody else.
      if ($user->user_avatar_type > 1) {
        $user->user_avatar = '';
      }

      $user->user_avatar = ($user->user_avatar) ? "$files_path/$pictures_path/$user->user_avatar" : '';

      // remove the :bbcode_uid from signature
      if (!empty($user->user_sig_bbcode_uid)) {
        $user->user_sig = preg_replace("/:$user->user_sig_bbcode_uid/", '', $user->user_sig);
      }
      $signature = _phpbb2drupal_strip_bbcode($user->user_sig);
      $signature = _phpbb2drupal_text_sanitise($signature);

      // Signatures for Forums module supports longer values than default 255 chars
      // http://drupal.org/project/signature_forum0
      if (!module_exists('signature_forum')) {
        $signature = substr($signature, 0, 255);
      }

      if (variable_get('phpbb2drupal_regdate_us_english', 0)) {
        $user_regdate = strtotime($user->user_regdate);
        $user_lastvisit = strtotime($user->user_lastvisit);
      }
      else {
        $user_regdate = $user->user_regdate;
        $user_lastvisit = $user->user_lastvisit;
      }

      //phpbb3 stores user status in user_type instead of user_active as phpbb2 did. inactive users get an id of 1. there are other status too, no idea what they mean.
      //KISS - user_type of 1 = inactive. The rest mean active.
      //further complication - duplicate check sets $user->user_active to 0 if the user is a duplicate.
      //Assume the only time the $user->user_active is set before now is in duplicate check and nothing is taken from database - so php isset() should work.
      if ($user->user_type <> 1 && !(isset($user->user_active))) {
        $user->user_active = 1;
      }

      $data = array(
      'name' => substr($user->username, 0, 60),
      'pass' => $user->user_password,
      'mail' => substr($user->user_email, 0, 64),
      'signature' => $signature,
      'created' => $user_regdate,
      'access' => $user_lastvisit,
      'login' => $user_lastvisit,
      'status' => $user->user_active,
      'timezone' => $user->user_timezone,
      'picture' => $user->user_avatar,
      'init' => substr($user->user_email, 0, 64),
      'roles' => array(0 => 2),                       # Authenticated User
      'user_website' => $user->user_website,
      'user_from' => $user->user_from,
      'user_icq' => $user->user_icq,
      'user_aim' => $user->user_aim,
      'user_yim' => $user->user_yim,
      'user_msnm' => $user->user_msnm,
      'user_occ' => $user->user_occ,
      'user_interests' => $user->user_interests
      );
      if (variable_get('phpbb2drupal_import_pm', 0)) {
        $data['privatemsg_allow'] = 1;
      }

      $data['user_interests'] = _phpbb2drupal_text_sanitise($data['user_interests']);

      db_set_active('default');
      $drupal_user = phpbb2drupal_user_save($data, array('account', 'Personal', 'Contact'));

      // populate the temporary user table
      db_set_active('default');

      $id = db_insert('phpbb2drupal_temp_user')
      ->fields(array(
        'user_id' => $user->user_id,
        'uid' => $drupal_user->uid,
      ))
      ->execute();

      db_set_active('phpbb');
    }
  }

  // set the user import successful flag in the variable table
  db_set_active('default');
  variable_set('phpbb2drupal_import_user_successful', '1');

  $count = db_query('SELECT COUNT(*) FROM {phpbb2drupal_temp_user}')->fetchField();
  drupal_set_message(t('Successfully Imported %count Users', array('%count' => $count)));
}

/**
 * Create Forum Containers and Forums
 */
function phpbb2drupal_import_categories() {
  // check if the forum database has been successfully imported
  db_set_active('default');
  if (variable_get('phpbb2drupal_import_category_successful', 0)) {
    drupal_set_message(t('Categories already imported successfully'));
    return;
  }

  // Retrieve the vocabulary vid named "Forum".
  $forum_vid = variable_get('forum_nav_vocabulary', 0);

  drupal_set_message(t('Forum vid: %forum_vid', array('%forum_vid' => $forum_vid)));

  // Get Categories/Forums from PHPBB
  db_set_active('phpbb');

  $results = db_query('SELECT * FROM {forums} WHERE forum_type <> :forum_type ORDER BY parent_id', array(':forum_type' => 2));

  foreach ($results as $result) {
    db_set_active('default');
    if (!db_query('SELECT forum_id FROM {phpbb2drupal_temp_forum} WHERE forum_id = :forum_id', array(':forum_id' => $result->forum_id))->fetchField()) {
      if ($result->parent_id > 0) {
        $result->parent_id = db_query('SELECT tid FROM {phpbb2drupal_temp_forum} WHERE forum_id = :forum_id', array(':forum_id' => $result->parent_id))->fetchField();
      }
      $forum = array(
        'name' => $result->forum_name,
        'vid' => $forum_vid,
        'description' => $result->forum_desc,
        'parent' => $result->parent_id,
      );
      $forum['name'] = _phpbb2drupal_text_sanitise($forum['name']);
      $forum['description'] = _phpbb2drupal_text_sanitise($forum['description']);
      
      $term = (object)$forum;

      taxonomy_term_save($term);

      // serialize the forum containers
      if ($result->forum_type == 0) {
        //This is a category
        $containers = variable_get('forum_containers', array());
        $containers[] = $term->tid;
        variable_set('forum_containers', $containers);
      }
      //save the container to the forum table - yes this is hackish.
      $id = db_insert('phpbb2drupal_temp_forum')
      ->fields(array(
        'forum_id' => $result->forum_id,
        'tid' => $term->tid,
      ))
      ->execute();
    }
    db_set_active('phpbb');
  }
  db_set_active('default');
  // set the forums import successful flag in the variable table
  variable_set('phpbb2drupal_import_category_successful', '1');

  $count = db_query('SELECT COUNT(*) FROM {phpbb2drupal_temp_forum}')->fetchField();
  drupal_set_message(t('Successfully Imported %count forums and containers.', array('%count' => $count)));
}

/**
 * Imports PHPBB topics to Drupal equivalent forum nodes
 */
function phpbb2drupal_import_topics() {
  $PHPBB2DRUPAL_IMPORT_ATTACHMENTS = variable_get('phpbb2drupal_import_attachments', 0);
  $input_format = variable_get('phpbb2drupal_input_format', 0);

  // check if the post database has been successfully imported
  db_set_active('default');
  if (variable_get('phpbb2drupal_import_topic_successful', 0)) {
    drupal_set_message(t('Topics already imported successfully'));
    return;
  }

  // Get All topics from PHPBB
  db_set_active('phpbb');
  // topic_status == 2, Moved topics are duplicates don't import
  $topic_ids = db_query('SELECT topic_id FROM {topics} ORDER BY topic_id');
  $topic_count = db_query('SELECT COUNT(*) FROM {topics}')->fetchField();
  drupal_set_message(t('Found %topic_count topics: Beginning Import', array('%topic_count' => $topic_count)));

  // Import the topics into drupal
  $counter = 0;
  db_set_active('phpbb');

  foreach ($topic_ids as $result) {
    // check if this topic has been imported already just to be sure
    db_set_active('default');
    $count = db_query('SELECT count(*) FROM {phpbb2drupal_temp_topic} WHERE topic_id = :topic_id', array(':topic_id' => $result->topic_id))->fetchField();
    if ($count > 0) {
      db_set_active('phpbb');
      continue;
    }

    db_set_active('phpbb');

    $query = db_query('SELECT *
      FROM {topics} t
      INNER JOIN {posts} p ON t.topic_id = p.topic_id WHERE ( p.post_id = t.topic_first_post_id
      AND t.topic_id = :topic_id )', array(':topic_id' => $result->topic_id));

    $querycount = db_query('SELECT COUNT(*)
      FROM {topics} t
      INNER JOIN {posts} p ON t.topic_id = p.topic_id WHERE p.post_id = t.topic_first_post_id
      AND t.topic_id = :topic_id', array(':topic_id' => $result->topic_id));


    // check if the topic is a valid topic.  if not, continue on
    if ($querycount->fetchField()) {
      $topic = db_query($query)->fetchObject();;
    }
    else {
      drupal_set_message(t('Could not find post details of topic: %topic_id', array('%topic_id' => $result->topic_id)));
      continue;
    }

    db_set_active('default');
    $uid = db_query('SELECT uid FROM {phpbb2drupal_temp_user} WHERE user_id = :user_id', array(':user_id' => $topic->topic_poster))->fetchField();
    $tid = db_query('SELECT tid FROM {phpbb2drupal_temp_forum} WHERE forum_id = :forum_id', array(':forum_id' => $topic->forum_id))->fetchField();

    if ($topic->topic_poster == 2) { // is the admin
      $user = array_shift(user_load_multiple(array(), array('name' => variable_get('phpbb2drupal_admin_user', ''))));
      $uid = $user->uid;
    }
    else if ($topic->topic_poster == -1) {
      $uid = 0;
    }

    if ($topic->topic_type == 1) {
      $sticky = 1; // sticky
      $promote = 0;
    }
    else if ($topic->topic_type == 2) {
      $sticky = 1;
      $promote = 0; // display on the front page, i.e. promote
    }
    else {
      $sticky = 0;
      $promote = 0;
    }

    if ($topic->topic_status == 1) { // LOCKED
      $comment = 1; // read-only
    }
    else { // UNLOCKED & WATCH NOTIFIED
      $comment = 2; // read-write
    }

    // remove the bbcode_uid from post_text
    if (!empty($topic->bbcode_uid)) {
      $topic->post_text = preg_replace("/:$topic->bbcode_uid/", '', $topic->post_text);
    }
    $topic->post_text = _phpbb2drupal_strip_bbcode($topic->post_text);
    $topic->post_text = _phpbb2drupal_text_sanitise($topic->post_text);

    if ($topic->post_edit_time < $topic->topic_time) {
      $topic->post_edit_time = $topic->topic_time;
    }

    // construct the node
    // Guide: http://timonweb.com/how-programmatically-create-nodes-comments-and-taxonomies-drupal-7
    
    $node = new stdClass(); // We create a new node object
    $node->type     = 'forum'; // Or any other content type you want
    $node->title    = _phpbb2drupal_text_sanitise($topic->topic_title);
    $node->language = LANGUAGE_NONE;
    $node->nid      = NULL;  //Not yet set, but http://drupal.org/node/839770 reccomends it to get past an error.
    $node->uid      = $uid;
    $node->status   = NODE_PUBLISHED; // published or not - always publish
    $node->promote  = $promote;
    $node->created  = $topic->topic_time;
    $node->changed  = $topic->post_edit_time;
    $node->comment  = $comment;
    $node->moderate = 0;
    $node->body[$node->language][0]['value'] = $topic->post_text;
    $node->body[$node->language][0]['format'] = $input_format;
    $node->sticky   = $sticky;

    if ($topic->topic_status == 2) {
      db_set_active('phpbb');
      $forum_id = db_query('SELECT forum_id FROM {topics} WHERE topic_id = :topic_id', array(':topic_id' => $topic->topic_moved_id))->fetchField();
      db_set_active('default');
      $moved_tid = db_query('SELECT tid FROM {phpbb2drupal_temp_forum} WHERE forum_id = :forum_id', array(':forum_id' => $forum_id))->fetchField();

      $node->taxonomy_forums[$node->language][]['tid'] = $moved_tid; // which forum it used to be part of
    }
    else {
      $node->taxonomy_forums[$node->language][]['tid'] = $tid;
    }


    db_set_active('default');
    node_submit($node);
    
    // $node->created is altered when calling node_submit(), re-enter the correct value.
    $node->created  = $topic->topic_time;
    
    node_save($node);

    if ($node->nid) {
      // Hack: Fix the node->changed in the db as node_save always sets it at the current time.
      db_update('node')
        ->fields(array(
          'changed' => $topic->post_edit_time,
        ))
      ->condition('nid', $node->nid)
      ->execute();

      // Hack: Keep the topics (that have no replies) in correct order by updating the
      // 'node_comment_statistics' table with the original topic creation time.
      db_update('node_comment_statistics')
        ->fields(array(
          'last_comment_timestamp' => $node->created,
        ))
      ->condition('nid', $node->nid)
      ->execute();
    }
    else {
      // Node import failed - display a message informing of failure.
      drupal_set_message(t('Failed importing %topic_id', array('%topic_id' => $topic->topic_id)));
    }

    // Handle attachments
    if ($PHPBB2DRUPAL_IMPORT_ATTACHMENTS) {
      if ($topic->topic_attachment == 1) {

        db_set_active('default');
        $file_path = variable_get('file_directory_path', 'files');

        db_set_active('phpbb');
        $files = db_query('SELECT * FROM {attachments} a WHERE a.post_msg_id = :a.post_msg_id', array(':a.post_msg_id' => $topic->topic_first_post_id));

        foreach ($files as $file) {
        
          db_set_active('default');

          $id = db_insert('files')->fields(array(
            'uid' => $uid,
            'filename' => substr($file->real_filename, 0, 255),
            'filepath' => substr( $file_path . $file->physical_filename, 0, 255),
            'filemime' => substr($file->mimetype, 0, 255),
            'filesize' => $file->filesize,
            'status' => 1,
            'timestamp' => $file->filetime,
          ))->execute();

          $fid = db_last_insert_id('files', 'fid');

          $id = db_insert('upload')
           ->fields(array(
            'fid' => $fid,
            'nid' => $node->nid,
            'vid' => $node->nid,
            'description' => substr($file->real_filename, 0, 255),
            'list' => 1,
            'weight' => $file->attach_id,
          ))
          ->execute();

          db_set_active('phpbb');
        }
      }
    }

    db_set_active('default');

    $id = db_insert('phpbb2drupal_temp_topic')
    ->fields(array(
        'topic_id' => $topic->topic_id,
        'post_id' => $topic->post_id,
        'nid' => $node->nid,
      ))
    ->execute();

    db_set_active('phpbb');
  }

  db_set_active('default');
  // set the topic import successful flag in the variable table
  variable_set('phpbb2drupal_import_topic_successful', '1');

  $count = db_query('SELECT COUNT(*) FROM {phpbb2drupal_temp_topic}')->fetchField();
  drupal_set_message(t('Successfully Imported %count topics', array('%count' => $count)));
}

/**
 * PHPBB Posts --> Drupal Comments
 */
function phpbb2drupal_import_posts() {
  $PHPBB2DRUPAL_IMPORT_ATTACHMENTS = variable_get('phpbb2drupal_import_attachments', 0);
  $input_format = variable_get('phpbb2drupal_input_format', 0);

  db_set_active('default');
  // check if the post database has been successfully imported
  if (variable_get('phpbb2drupal_import_post_successful', 0)) {
    drupal_set_message(t('Posts already imported successfully'));
    return;
  }

  if (!variable_get('phpbb2drupal_import_post_started', 0)) {
    db_set_active('default');
    variable_set('phpbb2drupal_import_post_started', 1);
  }

  db_set_active('phpbb');

  $topic_ids = db_query('SELECT topic_id, topic_first_post_id, topic_last_post_id
    FROM {topics}
    WHERE topic_replies > :topic_replies
    ORDER BY topic_id', array(':topic_replies' => 0));

  $topic_count = db_query("SELECT COUNT(topic_id) FROM {topics} WHERE topic_replies > :topic_replies", array(':topic_replies' => 0))->fetchField();
  drupal_set_message(t('Found %post_count posts: Beginning Import', array('%post_count' => $topic_count)));

  $errors = 0;
  $loops = 0;
  $imported = 0;
  // Import the posts into drupal
  foreach ($topic_ids as $obj) {
    $loops++;

    // skip first post if the post is not a poll
    // stupid phpbb... make the way you store topics consistent for crying out loud
    db_set_active('phpbb');
    $post_ids = db_query('SELECT post_id FROM {posts} WHERE topic_id = :topic_id AND post_id <> :post_id ORDER BY post_id', array(':topic_id' => $obj->topic_id, ':post_id' => $obj->topic_first_post_id));

    unset($obj);

    foreach ($post_ids as $result) {
    
      $loops++;

      db_set_active('phpbb');
      $query = db_query('SELECT * FROM {posts} WHERE post_id = :post_id', array(':post_id' => $result->post_id));
      $querycount = db_query('SELECT COUNT(*) FROM {posts} WHERE post_id = :post_id', array(':post_id' => $result->post_id));

      // make sure the post is valid
      if ($querycount->fetchField()) {
        $post = $query->fetchObject();
      }
      else {
        $errors++;
        drupal_set_message(t("Couldn't find post text for %post_id", array('%post_id' => $result->post_id)));
        continue;
      }

      // skip if the post has already been imported
      db_set_active('default');
      $count = db_query('SELECT COUNT(*) FROM {phpbb2drupal_temp_post} WHERE post_id = :post_id', array(':post_id' => $post->post_id))->fetchField();
      if ($count > 0) {
        $errors++;
        drupal_set_message(t('Post %post_id was already inserted', array('%post_id' => $post->post_id)));
        db_set_active('phpbb');
        continue;
      }

      db_set_active('default');
      $uid = db_query('SELECT uid FROM {phpbb2drupal_temp_user} WHERE user_id = :user_id', array(':user_id' => $post->poster_id))->fetchField();

      // get the node ID. The title may be useful further down if the comment doesn't have its own title.
      $node = db_query('SELECT n.nid, n.title FROM {phpbb2drupal_temp_topic} ptt LEFT JOIN {node_revision} AS n ON ptt.nid = n.nid  WHERE topic_id = :topic_id', array(':topic_id' => $post->topic_id))->fetchObject();
      $nid = $node->nid;

      $pid = db_query('SELECT MAX(pid) FROM {comment} WHERE nid = :nid', array(':nid' => $nid))->fetchField();

      $pid = (is_null($pid)) ? 0 : $pid;

      if ($post->poster_id == 2) { // is the admin
        $user = array_shift(user_load_multiple(array(), array('name' => variable_get('phpbb2drupal_admin_user', ''))));
        $uid = $user->uid;
      }
      else if ($post->poster_id == -1) { // anonymous
        $uid = 0;
      }

      $hostname = phpbb2drupal_decode_ip($post->poster_ip);

      // remove the :bbcode_uid from post_text
      if (!empty($post->bbcode_uid)) {
        $post->post_text = preg_replace("/:$post->bbcode_uid/", '', $post->post_text);
      }
      $post->post_text = _phpbb2drupal_strip_bbcode($post->post_text);
      $post->post_text = _phpbb2drupal_text_sanitise($post->post_text);
      $post->post_subject = _phpbb2drupal_text_sanitise($post->post_subject);

      // Construct the comment.
      $comment->pid = $pid;
      $comment->nid = $nid;
      $comment->uid = $uid;
      $comment->cid = 0; // leave it as is
      $comment->hostname = $hostname;
      $comment->language = LANGUAGE_NONE;
      $comment->is_anonymous = 0; // leave it as is
      $comment->created = $post->post_time;
      $comment->changed = empty($post->edit_time) ? $comment->created : $post->edit_time;
      $comment->status = $post->post_approved;
      $comment->subject = $post->post_subject;
      $comment->comment_body[$comment->language][0]['value'] = $post->post_text;
      $comment->comment_body[$comment->language][0]['format'] = $input_format;

      // if the title field is empty, use the node title as default.
      if (empty($comment->subject)) {
        $comment->subject = $node->title;
      }

      db_set_active('default');
      comment_submit($comment);

      // Override the comment created and changed time added in comment_submit() and then save.
      $comment->created = $post->post_time;
      $comment->changed = empty($post->edit_time) ? $comment->created : $post->edit_time;

      comment_save($comment);

      if (empty($comment->cid)) {
        $errors++;
        drupal_set_message(t('Failed importing %post_id', array('%post_id' => $post->post_id)));
      }

      // Handle attachments
      if ($PHPBB2DRUPAL_IMPORT_ATTACHMENTS) {
        if ($post->post_attachment == 1) {
          db_set_active('default');
          $file_path = variable_get('file_directory_path', 'files');

          db_set_active('phpbb');
          $files = db_query('SELECT * FROM {attachments} a WHERE a.post_msg_id = :a.post_msg_id', array(':a.post_msg_id' => $post->post_id));

          foreach ($files as $file) {
          
            db_set_active('default');
            $id = db_insert('files')
            ->fields(array(
              'uid' => $uid,
              'filename' => substr($file->real_filename, 0, 255),
              'filepath' => substr( $file_path . $file->physical_filename, 0, 255),
              'filemime' => substr($file->mimetype, 0, 255),
              'filesize' => $file->filesize,
              'status' => 1,
              'timestamp' => $file->filetime,
            ))
            ->execute();
            $fid = db_last_insert_id('files', 'fid');
            $id = db_insert('comment_upload')
            ->fields(array(
              'fid' => $fid,
              'nid' => $nid,
              'cid' => $comment->cid,
              'description' => substr($file->real_filename, 0, 255),
              'list' => 1,
              'weight' => $file->attach_id,
            ))
            ->execute();
            db_set_active('phpbb');
          }
        }
      }

      db_set_active('default');

      $id = db_insert('phpbb2drupal_temp_post')
      ->fields(array(
        'post_id' => $post->post_id,
        'cid' => $comment->cid,
      ))
      ->execute();

      $imported++;

      db_set_active('phpbb');
    }
  }

  // set the post import successful flag in the variable table
  db_set_active('default');
  variable_set('phpbb2drupal_import_post_successful', '1');
  drupal_set_message(t('Successfully Imported %imported posts', array('%imported' => $imported)));
  drupal_set_message(t('The were %loops loops executed', array('%loops' => $loops)));
  drupal_set_message(t('There %errors errors while importing posts', array('%errors' => $errors)));
}

/**
 * Clean UP
 */
function phpbb2drupal_import_cleanup() {
  variable_del('phpbb2drupal_table_prefix');
  variable_del('phpbb2drupal_db_database');
  variable_del('phpbb2drupal_db_username');
  variable_del('phpbb2drupal_db_password');
  variable_del('phpbb2drupal_db_host');
  variable_del('phpbb2drupal_db_driver');
  variable_del('phpbb2drupal_import_user_successful');
  variable_del('phpbb2drupal_import_user_started');
  variable_del('phpbb2drupal_import_category_successful');
  variable_del('phpbb2drupal_replace_url_successful');
  variable_del('phpbb2drupal_import_category_started');
  variable_del('phpbb2drupal_import_topic_successful');
  variable_del('phpbb2drupal_import_topic_started');
  variable_del('phpbb2drupal_import_post_successful');
  variable_del('phpbb2drupal_import_post_started');
  variable_del('phpbb2drupal_ready');
  variable_del('phpbb2drupal_regdate_us_english');
  variable_del('phpbb2drupal_input_format');
  variable_del('phpbb2drupal_databases');
  variable_del('phpbb2drupal_tested');
  variable_del('phpbb2drupal_same_db');
  variable_del('phpbb2drupal_table_prefix');
  variable_del('phpbb2drupal_time_limit');
  variable_del('phpbb2drupal_import_spammers');
  variable_del('phpbb2drupal_import_attachments');
  variable_del('phpbb2drupal_import_polls');
  variable_del('phpbb2drupal_import_poll_started');
  variable_del('phpbb2drupal_import_poll_successful');
  variable_del('phpbb2drupal_import_pm_successful');
  variable_del('phpbb2drupal_admin_user');
  variable_del('phpbb2drupal_encode');
  variable_del('phpbb2drupal_encoding_phpbb');
  variable_del('phpbb2drupal_encoding_drupal');
  variable_del('phpbb2drupal_version');

  db_delete('cache')
  ->execute();
}

/**
 * Helper Functions
 */
function phpbb2drupal_user_save($phpbb_user, $category = array()) {

  if (!($user = array_shift(user_load_multiple(array(), array('name' => $phpbb_user['name']))))) {
    $account = new stdClass();
    $account->uid = FALSE;
    $user = user_save($account, $phpbb_user);
    //Drupal overrides the phpBB user registration date when creating a Drupal account.
    //so we need to update it here.
    $user = user_save($user, array('created' => $phpbb_user['created']));

    //Insert the user password hash
    $result = db_update('users')
      ->fields(array(
        'pass' => $phpbb_user['pass'],
      ))
      ->condition('uid', $user->uid)
      ->execute();
    }
  $phpbb_user['uid'] = $user->uid;

  db_set_active('default');
  phpbb2drupal_profile_save_profile($phpbb_user, $user, $category); // add user profile information

  return $user;
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function phpbb2drupal_profile_save_profile(&$edit, &$user, $category) {
  $result = db_query('SELECT fid, name, type, category, weight FROM {profile_field} WHERE register = :register ORDER BY category, weight', array(':register' => 1));

  foreach ($result as $field) {
    if (_profile_field_serialize($field->type)) {
      $edit[$field->name] = serialize($edit[$field->name]);
    }

    db_delete('profile_value')
      ->condition('fid', $field->fid)
      ->condition('uid', $user->uid)
      ->execute();

    $id = db_insert('profile_value')
      ->fields(array(
        'fid' => $field->fid,
        'uid' => $user->uid,
        'value' => $edit[$field->name],
      ))
      ->execute();
    // Mark field as handled (prevents saving to user->data).
    $edit[$field->name] = NULL;
  }
}

/**
 * PHPBB function for decoding the user ip
 */
function phpbb2drupal_decode_ip($int_ip) {
  $hexipbang = explode('.', chunk_split($int_ip, 2, '.'));
  return hexdec($hexipbang[0]) . '.' . hexdec($hexipbang[1]) . '.' . hexdec($hexipbang[2]) . '.' . hexdec($hexipbang[3]);
}

/**
 * Strips text of extra phpbb3 markup and if requested, also strips all bbcode from text.
 */
function _phpbb2drupal_strip_bbcode($text) {
  // Strip the text of extra markup - regular expressions taken from phpbb3 includes/function.php, function get_preg_expression().
  $match = array(
    '#<!\-\- e \-\-><a href="mailto:(.*?)">.*?</a><!\-\- e \-\->#',
    '#<!\-\- l \-\-><a (?:class="[\w-]+" )?href="(.*?)(?:(&amp;|\?)sid=[0-9a-f]{32})?">.*?</a><!\-\- l \-\->#',
    '#<!\-\- ([mw]) \-\-><a (?:class="[\w-]+" )?href="(.*?)">.*?</a><!\-\- \1 \-\->#',
    '#<!\-\- s(.*?) \-\-><img src="\{SMILIES_PATH\}\/.*? \/><!\-\- s\1 \-\->#',
    '#<!\-\- .*? \-\->#s',
    '#<.*?>#s',
  );
  $replace = array('$1', '$1', '$2', '$1', '', '');
  $text = preg_replace($match, $replace, $text);

  // If bbcode conversion to has been selected, the following will convert the bbcode to normal html.
  if (variable_get('phpbb2drupal_bbcode', 0)) {
    $input_format = variable_get('phpbb2drupal_input_format', 0);
    $text = bbcode_filter('process', 0, $input_format, $text);
  }
  return $text;
}

/**
 * function to properly encode strings.
 */
function _phpbb2drupal_text_sanitise($text) {
  $text = html_entity_decode($text, ENT_QUOTES, 'utf-8');
  return $text;
}

// grep replace functions.
function _phpbb2drupal_replace_links_topic($matches) {
  //print_r($matches);
  $result = db_query('SELECT nid FROM {phpbb2drupal_temp_topic} WHERE topic_id = :topic_id', array(':topic_id' => $matches[1]))->fetchField();
  $link = 'node/' . $result . $matches[2];
  return $link;
}

function _phpbb2drupal_replace_links_post($matches) {
  //print_r($matches);
  $result = db_query('SELECT c.cid, c.nid FROM {phpbb2drupal_temp_post} p JOIN {comments} c ON c.cid = p.cid WHERE post_id = :post_id', array(':post_id' => $matches[1]))->fetchObject();
  $link = 'node/' . $result->nid . '#comment-' . $result->cid . $matches[3];
  return $link;
}

function _phpbb2drupal_replace_links_forum($matches) {
  //print_r($matches);
  $tid = db_query('SELECT tid FROM {phpbb2drupal_temp_forum} WHERE forum_id = :forum_id', array(':forum_id' => $matches[1]))->fetchField();
  $link = 'forum/' . $tid . $matches[2];
  return $link;
}


/**
 * Replace all types of links.
 */
function _phpbb2drupal_replace_links($html) {
  $html = preg_replace_callback('{forum/viewtopic.php\?p=(\d+)#(\d+)[^"|\'|>|<|\s|\]]*(["|\'|>|<|\s|\\|&quot;|\]])}i', '_phpbb2drupal_replace_links_post', $html);
  $html = preg_replace_callback('{forum/viewtopic.php\?t=(\d+)[^"|\'|>|<|\s|\]]*(["|\'|>|<|\s|\\|&quot;|\]])}i', '_phpbb2drupal_replace_links_topic', $html);
  $html = preg_replace_callback('{forum/viewforum.php\?f=(\d+)[^"|\'|>|<|\s|\]]*(["|\'|>|<|\s|\\|&quot;|\]])}i', '_phpbb2drupal_replace_links_forum', $html);
  // TODO look at removing $1.  it looks like dead code.
  $html = preg_replace('{forum/index.php[^"|\'|>|\s|\]]*(["|\'|<|>|\s|\\|&quot;|\]])}i', "forum$1", $html);
  // You can use the line below to test locally the url's when you are testing:
  //$html = preg_replace("{www.reuniting.info}i", "127.0.0.1/drupal", $html);
  return $html;
}


/**
 * Replace URLs to old phpBB forum to new Drupal forum
 */
function phpbb2drupal_replace_url() {
  db_set_active('default');

  // transform nodes:
  // As the topics have just been imported, there is only one vid for each nid,
  // so the query works as it is.
  $result = db_query('SELECT nid FROM {phpbb2drupal_temp_topic}');

  foreach ($result as $tt) {
  $fields = db_select('field_data_body', 'f')
    ->fields('f', array('body_value', 'body_summary'))
    ->condition('entity_type', 'node')
    ->condition('entity_id', $tt->nid)
    ->execute();

  foreach ($fields as $field) {
    db_update('field_data_body')
      ->fields(array(
        'body_value' => _phpbb2drupal_replace_links($field->body_value),
        'body_summary' => _phpbb2drupal_replace_links($field->body_summary),
      ))
      ->condition('entity_type', 'node')
      ->condition('entity_id', $tt->nid)
      ->execute();
  }

    // Transform urls in comments linked to this node.
    $cids = db_query('SELECT cid FROM {comment} WHERE nid = :nid', array(':nid' => $tt->nid));
    foreach ($cids as $cid) {
    $fields = db_select('field_data_comment_body', 'f')
      ->fields('f', array('comment_body_value'))
      ->condition('entity_type', 'comment')
      ->condition('entity_id', $cid)
      ->execute();
  
    foreach ($fields as $field) {
      db_update('field_data_comment_body')
        ->fields(array(
          'comment_body_value' => _phpbb2drupal_replace_links($field->comment_body_value),
        ))
        ->condition('entity_type', 'comment')
        ->condition('entity_id', $cid)
        ->execute();
      }
    }
  }
  variable_set('phpbb2drupal_replace_url_successful', '1');
}