<?php
/****************************************************
 * phpbb_redirect module: redirects links incoming from old phpBB forum to new Drupal forum.
 *
 ****************************************************/

/****************************************************
 *
 * Implementation of hook_help()
 *
 ****************************************************/
function phpbb_redirect_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#phpbb_redirect':
      $output = '<p>' . t('Redirects links to your old phpBB installation to the new Drupal forum.') . '</p>';
      $output .= '<p>' . t('This module requires <a href="@cleanurls">clean urls</a> to be active.', array('@cleanurls' => url('admin/config/search/clean-urls'))) . '</p>';
      $output .= '<p>' . t('phpBB_Redirect assumes that the old forum was located in the /forum folder. If that is not true, redirection will not work.') . '</p>';
      $output .= '<p>' . t('This can be worked around by either adding a redirect in the .htacceass file on apache installations or by manually editing the module.') . '</p>';
      $output .= '<p>' . t('If you choose to edit the module, all you need to do is change "forum/viewtopic.php" and "forum/viewtopic.php" in the "phpbb_redirect_menu" function. Just replace the "forum" bit with the real old location. e.g. if the old forums were located in the phpbb folder, change these paths to "phpbb/viewtopic.php" and "phpbb/viewtopic.php".') . '</p>';
      break;
  }
  return $output;
}


/****************************************************
 *
 * Implementation of hook_menu()
 *
 ****************************************************/
function phpbb_redirect_menu() {
  $items = array();

  $items['forum/viewtopic.php'] = array(
    'title' => 'Topic Redirect',
    'page callback' => 'phpbb_redirect_viewtopic',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  $items['forum/viewforum.php'] = array(
    'title' => 'Forum Redirect',
    'page callback' => 'phpbb_redirect_viewforum',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );

  return $items;
}

function phpbb_redirect_viewtopic() {
  if (isset($_GET['t']) && is_numeric($_GET['t'])) {
    $topic_id = $_GET['t'];

    $nid = db_query('SELECT nid FROM {phpbb2drupal_temp_topic} WHERE topic_id = :topic_id', array(':topic_id' => $topic_id))->fetchField();

    header('HTTP/1.1 301 Moved Permanently');
    drupal_goto("node/$nid");

  }
  else if (isset($_GET['p'])) {
    $post = explode('#', $_GET['p']);
    if (is_numeric($post[0])) {
      $post_id = $post[0];
    }
    else {
      drupal_goto('/');
    }

    $cid = db_query('SELECT cid FROM {phpbb2drupal_temp_post} WHERE post_id = :post_id', array(':post_id' => $post_id))->fetchField();
    $nid = db_query('SELECT nid FROM {comments} WHERE cid = :cid', array(':cid' => $cid))->fetchField();

    $node = node_load($nid);
    $mode = _comment_get_display_setting('mode', $node);

    $flat = in_array($mode, array(COMMENT_MODE_FLAT_COLLAPSED, COMMENT_MODE_FLAT_EXPANDED));
    if ($flat) {
      $comments_per_page = _comment_get_display_setting('comments_per_page', $node);
      $comment_count = db_query('SELECT COUNT(c.cid) FROM {comments} c WHERE c.nid = :c.nid AND c.status = :c.status AND c.cid < :c.cid', array(':c.nid' => $nid, ':c.status' => COMMENT_PUBLISHED, ':c.cid' => $cid))->fetchField();
      $page_number = floor($comment_count / $comments_per_page);
    }

    if (empty($page_number)) {
      $pagenum = NULL;
    }
    else {
      $pagenum = 'page=' . intval($page_number);
    }

    header('HTTP/1.1 301 Moved Permanently');
    // TODO "$pagenum" needs to be an array of keys and values instead of a string.
    drupal_goto("node/$nid", array('query' => "$pagenum", 'fragment' => "comment-$cid"));
  }
}

function phpbb_redirect_viewforum() {
  if (isset($_GET['f']) && is_numeric($_GET['f'])) {
    $forum_id = $_GET['f'];

    $tid = db_query('SELECT tid FROM {phpbb2drupal_temp_forum} WHERE forum_id = :forum_id', array(':forum_id' => $forum_id))->fetchField();

    header('HTTP/1.1 301 Moved Permanently');
    drupal_goto("forum/$tid");
  }
}

